sudo: required
services:
- docker

language: python

python:
- 3.5.0

script:
- echo "No build"

after_success:
- test $TRAVIS_PULL_REQUEST = false
  && docker login -u $DOCKER_USER -p $DOCKER_PASS
  && export REPO=gjtempleton/minion-solver
  && docker build -t $REPO:$COMMIT --build-arg GITSHA=$TRAVIS_COMMIT --build-arg BUILDDATE="`date`" .
  && docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  && if [[ "$TRAVIS_BRANCH" == "master" ]]; then docker tag $REPO:$COMMIT $REPO:latest; else docker tag $REPO:$COMMIT $REPO:$TRAVIS_BRANCH; fi
  && docker push $REPO
  && curl -X POST https://hooks.microbadger.com/images/gjtempleton/minion-solver

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: ejPBezHYOBL6UajA2P7Ak8fT03K7BIV3sTVPy0aG5NYPPrN82GjV0QUCDQB1usnyeL3qmgFBJx2Ui/09oQknweg73zjK2fLMifFmYYly5WkASd1VRlRw65NI7XDuRHx45b60AYM/mcjG26TFchdmzggagT+IpE2Sul6nqz37YZVnCSTl0R4Nsbk6AXWWd5M1L74GW5ptjBVt3yf4Ow5xRYFcHteNbFg+PfJkTqZ6/wLCnKHSvhruDL1QKyNIQdBlE78+iE4/EhlBXCFuDsVqIAPjztV/XHFHcgm/P9mTrK3ujAskhHx6bp4HD+hsoVJIkYHosOw7SXQ5/EHuZXXLqnSxuXQE4WPEeKjOiatWwuhkxb/OgotlL0EvMbZMkwXRC1Af+HGKE0/N+shtDp3Y65+tpbmessY6rr0BFHR4xfCwlSfo9i3/f3omkHYd6LsdPzqbpOvRxIzjhTQP0fXKk86MNkJ59vW9Omx4YrE3Fb6IvUr5Sedqy9PXs5+/pjEMhGYaVko7dt6pFzgYb8FPugmr+g7UTemXynVzGp/dLEGa0FcJ+2SZdQ91AR2M1Xkc9JhMWtS+aqLdB9ajRCmQZGBgCSXatV+JaPmUlI0I5YCHqllS4RnfzPc0IwH84ROD8BYkT5HG00u0W+P1onCaZsTi7Jcqm0gMX7/LJ+EEfnI=
  - secure: FeCB8l78bc1nzoDbmB4CT2MszITMK9Z6f0CS0m6kd3B7XnYvNum5tC7TsdABmeOakC7DrfpHYs5uOGgCU4mwEoK0CelieRsuCUWn/uGwEIg2T42+q7q3JQjkY47Mdh9bBtRCuxx/TnynJTmhiNp88hyGp7C91uFPi5WXTpr5RyPHVi5em4EXVbqIO01cfhtaO0BVrQJjZrnSd7+IV3ZAKgBrbsdsYQ7iFRKHeSiS5bdmKjik4ihN7Lesx0wabsLDCjjIya7KLXDhszICsL6lxHTym+HfxWsSArkQ7x6Z/Cd5zRICsDWMRYDyR4wiPW7rZf5pkyehi0gvS+96znJLX+c7xG3eEXBcItaNOm3KqgytUHVEzpF9pEx6LKjNO0xhT4E9nxqgYfbBfNfWZ4J12HmCNO4uzC74Fu5aUHBd9WVGjmJI7jCicvR5QYV1ayIJndLMbORQhdAPe1tBAbJ9qmazB/M+bjLJX3YW7SKiGiulGpcI8RnwQ6zX69S1ufQU9aAV6QYXf8YcQU4J1oTA4zvKlE6zRfYmNF8P0T2FcPGw+SD3jNG6dPhnvqcDofyD2dCApBkRdzbz/qSg/+b0Jk7zim0Cfdt3ZsE6RA36C2x29jtF03QCRAKieeeLQYhc5bHMWA4gkrXpBC7Wzj20FN5lqSCEyKTzORXhzA8o9hg=
